# Generated by Django 4.1.3 on 2022-11-15 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familiaresapp', '0005_primos_tios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='parentesco',
        ),
        migrations.RemoveField(
            model_name='primos',
            name='parentesco',
        ),
        migrations.RemoveField(
            model_name='tios',
            name='parentesco',
        ),
    ]
