# Generated by Django 4.1.3 on 2022-11-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiaresapp', '0006_remove_familia_parentesco_remove_primos_parentesco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='primos',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tios',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
