# Generated by Django 4.1.3 on 2022-11-16 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familiaresapp', '0007_alter_familia_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='fecha_nacimiento',
            new_name='fechanacimiento',
        ),
        migrations.RenameField(
            model_name='primos',
            old_name='fecha_nacimiento',
            new_name='fechanacimiento',
        ),
        migrations.RenameField(
            model_name='tios',
            old_name='fecha_nacimiento',
            new_name='fechanacimiento',
        ),
    ]
